# corpse_data.py

product_items = set([
    "FINE_ONYX_GEM",
    "FLAWLESS_ONYX_GEM",
    "FINE_PERIDOT_GEM",
    "FLAWLESS_PERIDOT_GEM",
    "FINE_CITRINE_GEM",
    "FLAWLESS_CITRINE_GEM",
    "FINE_AQUAMARINE_GEM",
    "FLAWLESS_AQUAMARINE_GEM",
    "SUSPICIOUS_SCRAP",
    "GOBLIN_EGG_BLUE",
    "REFINED_UMBER",
    "REFINED_TUNGSTEN",
    "REFINED_MITHRIL",
    "REFINED_TITANIUM",
    "GLACITE_AMALGAMATION",
    "UMBER_PLATE",
    "TUNGSTEN_PLATE",
    "UMBER_KEY",
    "TUNGSTEN_KEY",
    "GLACITE_JEWEL",
    "BEJEWELED_HANDLE",
    "ENCHANTMENT_ICE_COLD_1",
    "MITHRIL_PLATE",
    "SKELETON_KEY",
    "FLAWLESS_JASPER_GEM",
    "FLAWLESS_OPAL_GEM",
    "FLAWLESS_RUBY_GEM",
    "PERFECT_ONYX_GEM",
    "PERFECT_AQUAMARINE_GEM",
    "PERFECT_PERIDOT_GEM",
    "PERFECT_CITRINE_GEM",
    "PERFECT_JASPER_GEM",
    "PERFECT_OPAL_GEM"
])

umber_corpse = {
    "FINE_ONYX_GEM": [
        {"amount": 2, "weight": 800},
        {"amount": 4, "weight": 600},
        {"amount": 6, "weight": 400},
        {"amount": 8, "weight": 200},
    ],
    "FLAWLESS_ONYX_GEM": {"amount": 1, "weight": 10},
    "FINE_PERIDOT_GEM": [
        {"amount": 2, "weight": 800},
        {"amount": 4, "weight": 600},
        {"amount": 6, "weight": 400},
        {"amount": 8, "weight": 200},
    ],
    "FLAWLESS_PERIDOT_GEM": {"amount": 1, "weight": 10},
    "FINE_CITRINE_GEM": [
        {"amount": 2, "weight": 800},
        {"amount": 4, "weight": 600},
        {"amount": 6, "weight": 400},
        {"amount": 8, "weight": 200},
    ],
    "FLAWLESS_CITRINE_GEM": {"amount": 1, "weight": 10},
    "FINE_AQUAMARINE_GEM": [
        {"amount": 2, "weight": 800},
        {"amount": 4, "weight": 600},
        {"amount": 6, "weight": 400},
        {"amount": 8, "weight": 200},
    ],
    "FLAWLESS_AQUAMARINE_GEM": {"amount": 1, "weight": 10},
    "SUSPICIOUS_SCRAP": {"amount": 1, "weight": 250},
    "GOBLIN_EGG_BLUE": {"amount": 1, "weight": 100},
    "REFINED_UMBER": {"amount": 1, "weight": 80},
    "REFINED_TUNGSTEN": {"amount": 1, "weight": 80},
    "REFINED_MITHRIL": {"amount": 1, "weight": 60},
    "REFINED_TITANIUM": {"amount": 1, "weight": 60},
    "GLACITE_AMALGAMATION": {"amount": 1, "weight": 80},
    "UMBER_PLATE": {"amount": 1, "weight": 25},
    "TUNGSTEN_PLATE": {"amount": 1, "weight": 25},
    "PERFECT_ONYX_GEM": {"amount": 1, "weight": 50},
    "PERFECT_AQUAMARINE_GEM": {"amount": 1, "weight": 50},
    "PERFECT_PERIDOT_GEM": {"amount": 1, "weight": 50},
    "PERFECT_CITRINE_GEM": {"amount": 1, "weight": 50},
    "PERFECT_JASPER_GEM": {"amount": 1, "weight": 50},
    "PERFECT_OPAL_GEM": {"amount": 1, "weight": 50},
    "UMBER_KEY": {"amount": 1, "weight": 10},
    "TUNGSTEN_KEY": {"amount": 1, "weight": 10},
    "GLACITE_JEWEL": {"amount": 2, "weight": 250},
    "BEJEWELED_HANDLE": {"amount": 1, "weight": 175},
    "ENCHANTMENT_ICE_COLD_1": {"amount": 1, "weight": 150},
}

tungsten_corpse = {
    "FINE_ONYX_GEM": [
        {"amount": 2, "weight": 800},
        {"amount": 4, "weight": 600},
        {"amount": 6, "weight": 400},
        {"amount": 8, "weight": 200},
    ],
    "FLAWLESS_ONYX_GEM": {"amount": 1, "weight": 10},
    "FINE_PERIDOT_GEM": [
        {"amount": 2, "weight": 800},
        {"amount": 4, "weight": 600},
        {"amount": 6, "weight": 400},
        {"amount": 8, "weight": 200},
    ],
    "FLAWLESS_PERIDOT_GEM": {"amount": 1, "weight": 10},
    "FINE_CITRINE_GEM": [
        {"amount": 2, "weight": 800},
        {"amount": 4, "weight": 600},
        {"amount": 6, "weight": 400},
        {"amount": 8, "weight": 200},
    ],
    "FLAWLESS_CITRINE_GEM": {"amount": 1, "weight": 10},
    "FINE_AQUAMARINE_GEM": [
        {"amount": 2, "weight": 800},
        {"amount": 4, "weight": 600},
        {"amount": 6, "weight": 400},
        {"amount": 8, "weight": 200},
    ],
    "FLAWLESS_AQUAMARINE_GEM": {"amount": 1, "weight": 10},
    "SUSPICIOUS_SCRAP": {"amount": 1, "weight": 250},
    "GOBLIN_EGG_BLUE": {"amount": 1, "weight": 100},
    "REFINED_UMBER": {"amount": 1, "weight": 80},
    "REFINED_TUNGSTEN": {"amount": 1, "weight": 80},
    "REFINED_MITHRIL": {"amount": 1, "weight": 60},
    "REFINED_TITANIUM": {"amount": 1, "weight": 60},
    "GLACITE_AMALGAMATION": {"amount": 1, "weight": 80},
    "UMBER_PLATE": {"amount": 1, "weight": 25},
    "TUNGSTEN_PLATE": {"amount": 1, "weight": 25},
    "PERFECT_ONYX_GEM": {"amount": 1, "weight": 50},
    "PERFECT_AQUAMARINE_GEM": {"amount": 1, "weight": 50},
    "PERFECT_PERIDOT_GEM": {"amount": 1, "weight": 50},
    "PERFECT_CITRINE_GEM": {"amount": 1, "weight": 50},
    "PERFECT_JASPER_GEM": {"amount": 1, "weight": 50},
    "PERFECT_OPAL_GEM": {"amount": 1, "weight": 50},
    "UMBER_KEY": {"amount": 1, "weight": 10},
    "TUNGSTEN_KEY": {"amount": 1, "weight": 10},
    "GLACITE_JEWEL": {"amount": 2, "weight": 250},
    "BEJEWELED_HANDLE": {"amount": 1, "weight": 175},
    "ENCHANTMENT_ICE_COLD_1": {"amount": 1, "weight": 150},
}

vanguard_corpse = {
    "FLAWLESS_ONYX_GEM": {"amount": 1, "weight": 80},
    "FLAWLESS_PERIDOT_GEM": {"amount": 1, "weight": 80},
    "FLAWLESS_CITRINE_GEM": {"amount": 1, "weight": 80},
    "FLAWLESS_AQUAMARINE_GEM": {"amount": 1, "weight": 80},
    "FINE_ONYX_GEM": {"amount": 160, "weight": 40},
    "FINE_PERIDOT_GEM": {"amount": 160, "weight": 40},
    "FINE_CITRINE_GEM": {"amount": 160, "weight": 40},
    "FINE_AQUAMARINE_GEM": {"amount": 160, "weight": 40},
    "SUSPICIOUS_SCRAP": {"amount": 4, "weight": 150},
    "GOBLIN_EGG_BLUE": {"amount": 1, "weight": 140},
    "GOBLIN_EGG_BLUE": {"amount": 2, "weight": 70},
    "UMBER_KEY": {"amount": 1, "weight": 100},
    "UMBER_KEY": {"amount": 2, "weight": 50},
    "UMBER_KEY": {"amount": 4, "weight": 10},
    "TUNGSTEN_KEY": {"amount": 1, "weight": 100},
    "TUNGSTEN_KEY": {"amount": 2, "weight": 50},
    "TUNGSTEN_KEY": {"amount": 4, "weight": 10},
    "REFINED_UMBER": {"amount": 2, "weight": 80},
    "REFINED_TUNGSTEN": {"amount": 2, "weight": 80},
    "REFINED_MITHRIL": {"amount": 2, "weight": 60},
    "REFINED_TITANIUM": {"amount": 2, "weight": 60},
    "UMBER_PLATE": {"amount": 1, "weight": 50},
    "TUNGSTEN_PLATE": {"amount": 1, "weight": 50},
    "ENCHANTMENT_ICE_COLD_1": {"amount": 1, "weight": 150},
    "MITHRIL_PLATE": {"amount": 1, "weight": 30},
    "GLACITE_AMALGAMATION": {"amount": 2, "weight": 80},
    "GLACITE_AMALGAMATION": {"amount": 4, "weight": 40},
    "SKELETON_KEY": {"amount": 1, "weight": 6},
    "BEJEWELED_HANDLE": {"amount": 4, "weight": 150},
    "PERFECT_ONYX_GEM": {"amount": 1, "weight": 50},
    "PERFECT_AQUAMARINE_GEM": {"amount": 1, "weight": 50},
    "PERFECT_PERIDOT_GEM": {"amount": 1, "weight": 50},
    "PERFECT_CITRINE_GEM": {"amount": 1, "weight": 50},
    "PERFECT_JASPER_GEM": {"amount": 1, "weight": 50},
    "PERFECT_OPAL_GEM": {"amount": 1, "weight": 50}
}

# Define a mapping for PERFECT to FLAWLESS items
perfect_to_flawless = {
    "PERFECT_ONYX_GEM": "FLAWLESS_ONYX_GEM",
    "PERFECT_AQUAMARINE_GEM": "FLAWLESS_AQUAMARINE_GEM",
    "PERFECT_PERIDOT_GEM": "FLAWLESS_PERIDOT_GEM",
    "PERFECT_CITRINE_GEM": "FLAWLESS_CITRINE_GEM",
    "PERFECT_OPAL_GEM": "FLAWLESS_OPAL_GEM",
    "PERFECT_JASPER_GEM": "FLAWLESS_JASPER_GEM",
}